name: SharletPConsole.js: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: SharletPConsole.js: Lint
      run: |
        npm install -g eslint && eslint .
      env:
        CI: true
    - name: SharletPConsole.js: Test #Logs
      run: |
        npm install -g ts-node && npm run test:logs
      env:
        CI: true